### PR TITLE
Rename classes and fix compile

### PR DESCRIPTION
**Pull request by pjfanning**
* still broken because createSheetInjector override needs to be fixed

### CODE REVIEW

**Comment by pjfanning** [comment]
@mobreza One thing that confuses me in your branch is where is the class that implements IRowGenerator?

**Comment by mobreza** [comment]
The code that adds the bulk of rows to the sheet is deferred. The `IRowGenerator` is just a utility that provides access to the sheet and I usually use anonymous methods.

Comparing the original [XSSFSheet howto](http://poi.apache.org/components/spreadsheet/how-to.html#sxssf):

```java
public static void main(String[] args) throws Throwable {
  SXSSFWorkbook wb = new SXSSFWorkbook(100); // keep 100 rows in memory, exceeding rows will be flushed to disk
  Sheet sh = wb.createSheet();
  for(int rownum = 0; rownum < 1000; rownum++){
    Row row = sh.createRow(rownum);
    for(int cellnum = 0; cellnum < 10; cellnum++){
        Cell cell = row.createCell(cellnum);
        String address = new CellReference(cell).formatAsString();
        cell.setCellValue(address);
    }
  }

  // Rows with rownum < 900 are flushed and not accessible
  for(int rownum = 0; rownum < 900; rownum++){
    Assert.assertNull(sh.getRow(rownum));
  }

  // ther last 100 rows are still in memory
  for(int rownum = 900; rownum < 1000; rownum++){
    Assert.assertNotNull(sh.getRow(rownum));
  }

  FileOutputStream out = new FileOutputStream("/temp/sxssf.xlsx");
  wb.write(out);
  out.close();

  // dispose of temporary files backing this workbook on disk
  wb.dispose();
}
```

with the deferred row writer. The bulky part of XML generation happens while streaming to the target output stream:

```java
public static void main(String[] args) throws Throwable {
  SuperSXSSFWorkbook wb = new SuperSXSSFWorkbook(100);
  Sheet sh = wb.createSheet();
  // Do small things with the sheet, e.g. add headers, styles
  // as this code executes before wb.write() is called

  final SuperSXSSFSheet sheet = wb.getStreamingSheet(sh.getSheetName());
  // Set up deferred row generation
  sheet.setRowGenerator((sh) -> {
    // This code is the same, but it executes while writing to the final output stream
    for(int rownum = 0; rownum < 1000; rownum++){
      Row row = sh.createRow(rownum);
      for(int cellnum = 0; cellnum < 10; cellnum++){
          Cell cell = row.createCell(cellnum);
          String address = new CellReference(cell).formatAsString();
          cell.setCellValue(address);
      }
    }
    // Rows with rownum < 900 are flushed and not accessible
    for(int rownum = 0; rownum < 900; rownum++){
      Assert.assertNull(sh.getRow(rownum));
    }
    // ther last 100 rows are still in memory
    for(int rownum = 900; rownum < 1000; rownum++){
      Assert.assertNotNull(sh.getRow(rownum));
    }
  });

  // This point is reached quickly because we don't generate the rows to the temp disk file used by 
  // SXSSF, but write them while streaming to the final target stream (think HTTP response):
  FileOutputStream out = new FileOutputStream("/temp/sxssf.xlsx");
  wb.write(out);
  out.close();

  // dispose of temporary files backing this workbook on disk
  wb.dispose();
}
```

**Comment by mobreza** [comment]
>     * createSheetInjector

Let me have a look at the code again, I quickly rebased it on current master to get the conversation going.

**Comment by mobreza** [comment]
I managed to mess up this MR with a rebase of the target branch on current trunk. Sorry.

https://github.com/apache/poi/pull/184 contains the relevant code changes.

**Pull request closed without merging**
